### ISSUE TITLE
#Проработка Имплементация "А потом ты проснулся"

### ISSUE THREAD

**Issue by ImperatorOfIntellectualism** [GlybaSketch-maintainer/GlybaSketch#12]
Обработчик эксэпшонов должен выглядеть следующим образом:
```
АвэкейнПойнт_Функция = Функция().Проснулся?
Авэкейн (АвэкейнПоинт)
```
Если АвэкейнПоинт содержит ошибку, то Авэкейн вызывает сообщение:

>АвэкейнПоинт_Функция содержит ошибку "Бла-бла-бла"

А потом ты проснулся.

Ну, что вы думаете коллеги? Мнение? Идеи? Предложения?

**Comment by Aarnihauta** [comment]
Коллега, идея отличная, принято
